from tkinter import*
from tkinter.ttk import*
root = Tk()
root.title("Coding Class Registeration")
root.geometry("400x400")
root.config(background = "light goldenrod yellow")
Label1 = Label(root, text = "Coding Class Registeration")
Label2 = Label(root, text = "Select Course")
Variable2 = StringVar()
Combobox1 = Combobox(root, textvariable = Variable2, width = 5)
Combobox1["values"] = tuple(("Scratch", "Microbit", "Cospaces", "Thunkable", "Makey-Makey", "Minecraft Education", "Roblox Education", "Codepen", "Python", "GUI"))
Variable1 = StringVar()
r1 = Radiobutton(root, variable = Variable1, text = "Morning, 10 A.M.", value = "Morning 10 A.M.")
r2 = Radiobutton(root, variable = Variable1, text = "Evening, 5 P.M.", value = "Evening 5 P.M.")
def write():
    Label3 = Label(root, text = "Thank you! You have been enrolled in " + (Variable2.get()) + " at " + (Variable1.get()))
    Label3.pack()
Button1 = Button(root,text = "Enroll Now!", command = write)
Label1.pack()
Label2.pack()
Combobox1.pack()
r1.pack()
r2.pack()
Button1.pack()
root.mainloop()
