from tkinter import*
root = Tk()
root.title("Memorizer")
root.geometry("400x400")
root.configure(background = "red")
Button1 = Button(root, text = "Save", bd = "4", fg = "black", width = 5)
Entry1 = Entry(root, width = 5)
Button2 = Button(root, text = "Open", bd = "4", fg = "black", width = 5)
Button3 = Button(root, text = "Add", bd = "4", fg = "black", width = 5)
Button4 = Button(root, text = "Delete", bd = "4", fg = "black", width = 5)
Button1.place(x = 170, y = 50)
Entry1.place(x = 185, y = 100)
Button2.place(x = 170, y = 150)
Button3.place(x = 0, y = 300)
Button4.place(x = 315, y = 300)
root.mainloop()