from tkinter import*
from tkinter.filedialog import*
root = Tk()
root.title("COLORS")
root.geometry("400x400")
root.config(background = "white")
Scroll1 = Scrollbar(root)
Listbox1 = Listbox(root, width = 25, height = 10, background = "silver", yscrollcommand = Scroll1.set)
Listbox1.insert(END, "red")
Listbox1.insert(END, "orange")
Listbox1.insert(END, "yellow")
Listbox1.insert(END, "green")
Listbox1.insert(END, "blue")
Listbox1.insert(END, "purple")
Listbox1.insert(END, "pink")
Listbox1.insert(END, "gold")
Listbox1.insert(END, "silver")
Listbox1.insert(END, "light blue")
Listbox1.insert(END, "light green")
Listbox1.insert(END, "brown")
Listbox1.insert(END, "tan")
Listbox1.insert(END, "maroon")
Listbox1.pack()
Scroll1.pack(side = RIGHT)
def Colors():
    Index = Listbox1.curselection()
    if Index:
        color = Listbox1.get(Index)
        root.config(background = color)
Apply = Button(root, text = "Apply Color", fg = "black", command = Colors)
Apply.pack()
root.mainloop()