from tkinter import*
root = Tk()
life = Menu(root, fg = "black")
file = Menu(life, fg = "black")
life.add_cascade(label = "File", menu = file)
file.add_command(label = "New file", command = None)
file.add_separator()
file.add_command(label = "Open file", command = None)
file.add_separator()
file.add_command(label = "Edit file", command = None)
file.add_separator()
file.add_command(label = "Save file", command = None)
file.add_separator()
file.add_command(label = "Close file", command = None)
root.config(menu = life)
root.mainloop()