from tkinter import*
root = Tk()
root.title("Tkinker Menu... 2.0")
root.geometry("400x400")
root.configure(background = "red")
Star = Label(root, text = "Email", fg = "black")
Star2 = Entry(root, width = "100")
Space = Label(root, text = "password", fg = "black")
Space2 = Entry(root, width = "100")
Sun = Label(root, text = "What do you want? Chili Paneer, Tomyom Soup, or None?")
Sun2 = Entry(root, width = "100")
Sun3 = Spinbox(root, from_=0, to=10)
Moon = Label(root, text = "What do you want? Noodles, Momos, or None?")
Moon2 = Entry(root, width = "100")
Moon3 = Spinbox(root, from_=0, to=10)
Asteroid = Label(root, text = "What do you want? Ice Cream, Brownies, or None?")
Asteroid2 = Entry(root, width = "100")
Asteroid3 = Spinbox(root, from_=0, to=10)
Star.pack()
Star2.pack()
Space.pack()
Space2.pack()
Sun.pack()
Sun2.pack()
Sun3.pack()
Moon.pack()
Moon2.pack()
Moon3.pack()
Asteroid.pack()
Asteroid2.pack()
Asteroid3.pack()
root.mainloop()