from tkinter import*
root = Tk()
root.title("Adress Book")
root.geometry("400x400")
root.config(background = "light green")
Label1 = Label(root, text = "My Address Book", fg = "black")
Label2 = Label(root, text = "Name", fg = "black")
Label3 = Label(root, text = "Address", fg = "black")
Label4 = Label(root, text = "Mobile", fg = "black")
Label5 = Label(root, text = "Email", fg = "black")
Label6 = Label(root, text = "Birthday", fg = "black")
Button1 = Button(root, text = "Open",bd = 4, fg = "black")
Button2 = Button(root, text = "Edit",bd = 4, fg = "black")
Button3 = Button(root, text = "Delete",bd = 4, fg = "black")
Button4 = Button(root, text = "Update/Add",bd = 4, fg = "black")
Button5 = Button(root, text = "Save",bd = 4, fg = "black")
Entry1 = Entry(root, width = 30)
Entry2 = Entry(root, width = 30)
Entry3 = Entry(root, width = 30)
Entry4 = Entry(root, width = 30)
Entry5 = Entry(root, width = 30)
Label1.place(x = 0, y = 0)
Label2.place(x = 250, y = 50)
Entry1.place(x = 250, y = 75)
Label3.place(x = 250, y = 100)
Entry2.place(x = 250, y = 125)
Label4.place(x = 250, y = 150)
Entry3.place(x = 250, y = 175)
Label5.place(x = 250, y = 200)
Entry4.place(x = 250, y = 225)
Label6.place(x = 250, y = 250)
Entry5.place(x = 250, y = 275)
Button1.place(x = 0, y = 350)
Button2.place(x = 75, y = 350)
Button3.place(x = 150, y = 350)
Button4.place(x = 225, y = 350)
Button5.place(x = 330, y = 350)
root.mainloop()