from tkinter import*
root = Tk()
root.title("Jumbled Word Game")
root.geometry("400x400")
root.config(background = "black")
Label1 = Label(root, text = "Jumbled Word Game", fg = "black")
Label2 = Label(root, text = "aroirwsr", fg = "black")
Entry1 = Label(root, width = 30)
Button1 = Button(root, text = "Check", bd = 4, fg = "black")
Button2 = Button(root, text = "Reset", bd = 4, fg = "black")
Label1.place(x = 135, y = 25)
Label2.place(x = 175, y = 105)
Entry1.place(x = 62, y = 130)
Button1.place(x = 165,y = 190)
Button2.place(x = 168,y = 250)
root.mainloop()